config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do 
    resources :comments, only: [:create] do
      member do
        post 'vote'
        patch 'vote_change'     
      end
    end

    member do
      post 'vote'
      patch 'vote_change'
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :edit, :update, :show, :index,]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable #this module is in /lib folder
  include Sluggable

  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote, :vote_change]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator_or_admin, only: [:edit ,:update]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Your post was created!"
      redirect_to posts_path
    else
      render :new #this could also be written using symbol 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was edited!"
      redirect_to post_path(@post)
    else
      render :edit #or 'edit'
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])
    #@vote.user = current_user
    #@vote.voteable = @post

    respond_to do |format| #this is AJAX
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "You can only vote on a post once"
        end

        redirect_to :back
      end
      format.js {} #nothing's here, default action in Rails is render
                  # ---> thus this will try to render a vote.js.erb template
    end
  end

  def vote_change
    @vote = @post.votes.find_by user_id: current_user.id
    @vote.old_vote = @vote[:vote]
    @vote.new_vote = params[:vote]

    respond_to do |format|
      format.html do
        if @vote.valid?
          @vote.update(vote: params[:vote])
          flash[:notice] = "Your vote was changed"
        else
          flash[:error] = "You only have one vote (up or down)"
        end
        redirect_to :back
      end
      format.js do
        if @vote.valid?
          @vote.update(vote: params[:vote])
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, :user, category_ids: []) #could change to .permit! if permitting all
  end

  def set_post
    #@post = Post.find_by params[:slug]
    @post = Post.find_by(slug: params[:id])
  end

  def user_is_creator?
    current_user == @post.user
  end

  def require_creator
    access_denied unless logged_in? && user_is_creator?
  end

  def require_creator_or_admin
    access_denied unless logged_in? && (user_is_creator? || current_user.is_admin?)
  end
end

app/views/posts/_comment.html.erb
<% show_comment_post ||= false %> <!-- this sets this var as a default to false (if no value is passed to it) -->

<div class="row">
  <div class="span2 well text-center">
    <% if logged_in? %>
      <div id="vote_up_<%= comment.id %>">
        <% if user_voted?(comment) %>
          <%= link_to vote_change_post_comment_path(comment.post, comment, vote: true), method: 'patch', remote: true do %>
            <i class="icon-circle-arrow-up"></i>
          <% end %>        
        <% else %>
          <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
            <i class="icon-circle-arrow-up"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %></span>
    <% if comment.total_votes == 1 || comment.total_votes == -1 %>
      vote
    <% else %>
      votes
    <% end %>
    <% if logged_in? %>
      <div id="vote_down_<%= comment.id %>">
        <% if user_voted?(comment) %>
          <%= link_to vote_change_post_comment_path(comment.post, comment, vote: false), method: 'patch', remote: true do %>
            <i class="icon-circle-arrow-down"></i>
          <% end %>        
        <% else %>
          <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
            <i class="icon-circle-arrow-down"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <% if logged_in? %>
      <div class="well well-small" id="user_vote_<%= comment.id %>">
        <% if user_voted?(comment) %>
          <small>your vote: <%= vote_for_show(comment) %></small>
        <% else %>
          <small>your vote: none</small>
        <% end %>
      </div>
    <% end %>
    <span id="comment_<%= comment.id %>_msg"></span>
  </div>

  <div class="well span8">
    <p>
      <%= comment.body %> <span class="quiet">
      <% if show_comment_post %>
        on</span> <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
    </p>
    <br/>
    <span class="quiet">comment by </span><%= link_to comment.user.username, user_path(comment.user.id) %>
    <small>at <%= pretty_date_time(comment.created_at) %></small>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="well">
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>    
    <div class='control-group'>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, size: "10x10" %>
    </div>
    <br/>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
    <% end %>
    <br/>
    <%= f.submit action_description, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span2 well text-center">
    <% if logged_in? %>
      <div id="vote_up_<%= post.id %>">
        <% if user_voted?(post) %>
          <%= link_to vote_change_post_path(post, vote: true), method: 'patch', remote: true do %>
            <i class="icon-circle-arrow-up"></i>
          <% end %>        
        <% else %>
          <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
            <i class="icon-circle-arrow-up"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <span id="post_<%= post.id %>_votes"><%= post.total_votes %></span>
    <% if post.total_votes == 1 || post.total_votes == -1 %>
      vote
    <% else %>
      votes
    <% end %>
    <% if logged_in? %>
      <div id="vote_down_<%= post.id %>">
        <% if user_voted?(post) %>
          <%= link_to vote_change_post_path(post, vote: false), method: 'patch', remote: true do %>
            <i class="icon-circle-arrow-down"></i>
          <% end %>        
        <% else %>
          <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
            <i class="icon-circle-arrow-down"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if logged_in? %>
      <div class="well well-small" id="user_vote_<%= post.id %>">
        <% if user_voted?(post) %>
          <small>your vote: <%= vote_for_show(post) %></small>
        <% else %>
          <small>your vote: none</small>
        <% end %>
      </div>
    <% end %>
    <span id="post_<%= post.id %>_msg"></span>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by </span><%= link_to post.user.username, user_path(post.user) %>
      <small>at <%= pretty_date_time(post.created_at) %></small> <!-- post.created_at -->
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        <% if logged_in? && (post.user == current_user || current_user.is_admin?) %>
          <%= link_to("Edit", edit_post_path(post), class: "right") %>
        <% end %>
      </span>
    </small>
  </div>
</div>

app/views/posts/comment_vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%= @comment.id %>_votes').html('<%= @comment.total_votes %>');
  $('#comment_<%= @comment.id %>_msg').addClass("alert alert-success").html("<small>Vote Counted!</small>");

  $('#vote_up_<%= @comment.id %>').replaceWith( '<div><%= link_to vote_change_post_comment_path(@comment.post, @comment, vote: true), method: 'patch', remote: true do %><i class="icon-circle-arrow-up"></i><% end %></div>');
  $('#vote_down_<%= @comment.id %>').replaceWith( '<div><%= link_to vote_change_post_comment_path(@comment.post, @comment, vote: false), method: 'patch', remote: true do %><i class="icon-circle-arrow-down"></i><% end %></div>');
  $('#user_vote_<%= @comment.id %>').html('<small>your vote: <%= vote_for_show(@comment) %></small>')
<% else %>
  $('#comment_<%= @comment.id %>_msg').addClass("alert alert-error").html("<small>Already Voted</small>");
<% end %>

app/views/posts/comment_vote_change.js.erb
<% if @vote.valid? %>
  $('#comment_<%= @comment.id %>_votes').html('<%= @comment.total_votes %>');
  $('#comment_<%= @comment.id %>_msg').removeClass("alert-error").addClass("alert alert-success").html("<small>Vote Changed!</small>");
  $('#user_vote_<%= @comment.id %>').html('<small>your vote: <%= vote_for_show(@comment) %></small>')
<% else %>
  $('#comment_<%= @comment.id %>_msg').removeClass("alert-success").addClass("alert alert-error").html("<small>Already Voted</small>");
<% end %>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit Your Post" %>

<%= render 'shared/validation_error', object: @post %>

<%= render 'form', action_description: 'Edit' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.reverse.each do |post| %>
  <%= render 'post', post: post %> <!-- we need to pass in the local variable (unlike instance variables, which are by default read by views (HTML)) -->
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a New Post" %>

<%= render 'shared/validation_error', object: @post %>

<%= render 'form', action_description: "Create Post" %>

app/views/posts/show.html.erb
<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: link_to("#{@post.title}", fix_url(@post))  %>

<p>
  <%= @post.description %>
</p>
<br/>
<% if logged_in? && @post.user == current_user %>
  <small><%= link_to("Edit", edit_post_path(@post), class: 'right') %></small>
<% end %>
<br/>

<hr/>

<!-- this below is code created by me to just try things out -->

<h4>Comments:</h4>

<% @post.reload.comments.each do |comment| %>
  <%= render 'posts/comment', comment: comment %>
<% end %>

<!-- .reload method fixes the bug when our comment fails validation (comment is saved in memory and associated to the @post object and our code tries to render a view for it but can't) - .reload just uses the data from our database and updates (re-freshes) it as @post.comments (without this last comment, that was saved in memory) -->
<!-- I actually don't need that here, since I used .new method in my comments#create action, instead of .create (or .build), so this is actually not saved. This would be needed if using the syntax from solutions -->

<hr/>

<!-- comments create form -->

<%= render 'shared/validation_error', object: @comment %>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body %>
    <br/>
    <%= f.submit "Add Comment", class: "btn btn-primary" %>
  <% end %>
<% else %>
  <h4 class="text-center">You must be logged in to comment</h4>
<% end %>

app/views/posts/vote.js.erb
//alert("total votes for <%= @post.title %> is <%= @post.total_votes %>");
<% if @vote.valid? %>
  $('#post_<%= @post.id %>_votes').html('<%= @post.total_votes %>');
  $('#post_<%= @post.id %>_msg').addClass("alert alert-success").html("<small>Vote Counted!</small>");
  $('#vote_up_<%= @post.id %>').replaceWith( '<div><%= link_to vote_change_post_path(@post, vote: true), method: 'patch', remote: true do %><i class="icon-circle-arrow-up"></i><% end %></div>');
  $('#vote_down_<%= @post.id %>').replaceWith( '<div><%= link_to vote_change_post_path(@post, vote: false), method: 'patch', remote: true do %><i class="icon-circle-arrow-down"></i><% end %></div>');
  $('#user_vote_<%= @post.id %>').html('<small>your vote: <%= vote_for_show(@post) %></small>')
<% else %>
  //alert("You can only vote on that once");
  $('#post_<%= @post.id %>_msg').addClass("alert alert-error").html("<small>Already Voted</small>");
<% end %>

app/views/posts/vote_change.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.id %>_votes').html('<%= @post.total_votes %>');
  $('#post_<%= @post.id %>_msg').removeClass("alert-error").addClass("alert alert-success").html("<small>Vote Changed!</small>");
  $('#user_vote_<%= @post.id %>').html('<small>your vote: <%= vote_for_show(@post) %></small>')
<% else %>
  $('#post_<%= @post.id %>_msg').removeClass("alert-success").addClass("alert alert-error").html("<small>Already Voted</small>");
<% end %>